apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: a6423175-0dbb-40f6-90db-480ea8d99d74
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: ${PGDATABASE}
    user: ${PGUSER}
    secureJsonData:
      password: ${PGPASSWORD}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1400
      timescaledb: true
